# SEE: https://github.com/gitleaks/gitleaks/#configuration
[extend]
useDefault = true # SEE: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
[[rules]]
description = "IPv4"
id = "ipv4"
regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''
[rules.allowlist]
regexTarget = "match"
regexes = [
  # Exclude the private network IPv4 addresses as well as the DNS servers for Google and OpenDNS
  '''(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3}|0\.0\.0\.0|255\.255\.255\.255|8\.8\.8\.8|8\.8\.4\.4|208\.67\.222\.222|208\.67\.220\.220)'''
]
[allowlist]
paths = ['''.terraform.lock.hcl''', '''poetry.lock''', '''yarn.lock''']
regexes = [
# Known false-positive Azure client / role IDs
'''abfa0a7c-a6b6-4736-8310-5855508787cd''',
'''205478c0-bd83-4e1b-a9d6-db63a3e1e1c8''',
'''ec156ff8-a8d1-4d15-830c-5b80698ca432''',
'''4633458b-17de-408a-b874-0445c86b69e6''',
'''f58310d9-a9f6-439a-9e8d-f62e7b41a168''',
'''acdd72a7-3385-48ef-bd42-f606fba81ae7''',
'''b24988ac-6180-42a0-ab88-20f7382dd24c''',
'''ba92f5b4-2d11-453d-a403-e96b0029c9fe''',
'''b86a8fe4-44ce-4948-aee5-eccb2c155cd7''',
'''3466794b-ae91-4039-a834-c2d888c78a53''',
'''f1a07417-d97a-45cb-824c-7a7467783830''',
'''18d7d88d-d35e-4fb5-a5c3-7773c20a72d9'''
]
